# Phase 3b: DSPy Query Generation Optimization
# Goal: Add query generation optimization on top of Phase 3a (~47% target)

phase: 3b_dspy_query_gen
description: "DSPy MIPROv2 optimization with query generation added"

# Optimization settings
optimization:
  query_optimization: true  # YES - query generation in Phase 3b
  optimize_components:
    - QueryGeneration   # NEW: Learnable query reformulation
    - ESGReasoning      # Continue optimizing reasoning
    - AnswerExtraction  # Continue optimizing extraction

  optimizer: MIPROv2
  mode: medium  # 10-15 trials, ~30-45 minutes
  num_candidates: 15
  num_threads: 4

  # Use explicit valset for fair comparison
  use_explicit_valset: true

  # Start from Phase 3a optimized prompts
  initialize_from_phase3a: true
  phase3a_module_path: "phase3a_dspy_prompts/optimized_module.json"

# Dataset splits (same as Phase 3a)
data:
  train_size: 186  # 20% for optimization
  dev_size: 93     # 10% for validation
  test_size: 654   # 70% held out

  dataset_path: "mmesgbench_dataset_corrected.json"
  use_existing_splits: true

# Retrieval settings (NOW with query generation)
retrieval:
  method: semantic_search_with_query_gen
  embedding_model: text-embedding-v4
  embedding_dim: 1024
  vector_store: pgvector
  collection_name: MMESG
  top_k: 5

  # Query generation module enabled
  query_generation: true
  query_gen_model: qwen-max

# LLM settings
llm:
  provider: dashscope
  model: qwen-max
  temperature: 0.0
  max_tokens: 2048

# Evaluation
evaluation:
  metrics:
    - retrieval_accuracy  # RESEARCH metric (should improve with better queries)
    - answer_accuracy     # PRIMARY metric (for MMESGBench comparison)
    - e2e_accuracy        # RESEARCH metric

  use_mmesgbench_eval: true  # Use their exact eval_score()
  anls_threshold: 0.5        # Fuzzy matching threshold

# Experiment tracking
tracking:
  use_mlflow: true
  experiment_name: "Phase3b_DSPy_QueryGen"
  log_artifacts: true
  log_params: true
  log_metrics: true

# Output
output:
  results_dir: "phase3b_dspy_query_gen/results"
  checkpoint_dir: "phase3b_dspy_query_gen/checkpoints"
  optimized_module_path: "phase3b_dspy_query_gen/optimized_module.json"
